### ISSUE TITLE
jenkins slave node locale not set

### ISSUE THREAD

**Issue by zette** [atteo/jfactory#15]
There is a problem with jenkins slave nodes stared as docker containers.
The container and jenkins-agent does not have locale set to utf-8. When project uses filenames encoded in UTF-8, problems start to come up.
```
Exception thrown: java.io.IOException: remote file operation failed: /home/jenkins/workspace/project_path at hudson.remoting.Channel@6f532748:Channel to /172.179.0.1: java.io.IOException: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/jenkins/workspace/project_path/filename_in_UTF8
```

Consider setting UTF-8 for both: jenkins-slave container and jenkins-agent (-Dfile.encoding=UTF-8).

**Comment by sentinelt** [comment]
Thanks for the report. I will look at this later today.

**Comment by sentinelt** [comment]
Fixed. I have release 2.1 version with this fix. I tested this issue by creating a [repo](https://github.com/atteo/jfactory/tree/master/images/gerrit/initial_repositories/example-%C4%85%C4%87%C4%99%C3%B3%C5%82%C5%84%C5%9B%C5%BC%C5%BA%C4%84%C4%86%C4%98%C3%93%C5%81%C5%83%C5%9A%C5%BB%C5%B9) in Gerrit with various national characters in the name.

Please remember to upgrade slave versions to 2.1 in 'Manage Jenkins/Configure System/Cloud'. Valid versions are 'jfactory/cloud-slave:2.1', 'jfactory/java8-slave:2.1' and 'jfactory/javascript-slave:2.1'. This is not done yet automatically when upgrading.
